### ISSUE TITLE
Use NPM instead of PNPM

### ISSUE THREAD

**Issue by rafaelspring** [basaran/svelte-recaptcha-v2#12]
Would you mind moving svelte-recaptcha-v2 to NPM instead of PNPM?

Most people use NPM and I had lots of trouble with PNPM (https://github.com/pnpm/pnpm/issues/724#issuecomment-1464947089), that's why I'm unable to use svelte-recaptcha-v2, even though the project looks great and I'd really like to use it.

Please consider it. Thank you.

**Comment by basaran** [comment]
Hi there :)

You don't have to use pnpm, you can install the package with npm. I use pnpm myself that is why I put that in the readme. I will update it in the next revision to mention you can use your project's package manager to install the package from npm.
