### ISSUE TITLE
Debug/Browser.js does not provide an export named 'default'

### ISSUE THREAD

**Issue by bridge-jithesh** [basaran/svelte-recaptcha-v2#7]
I am having the below error while doing `import { Recaptcha, recaptcha, observer } from "svelte-recaptcha-v2";`

```
SyntaxError: The requested module '/node_modules/debug/src/browser.js?v=9e58a267' does not provide an export named 'default'
```

I am using:
```
"@sveltejs/kit": "^1.0.0-next.221"
"@sveltejs/adapter-node": "^1.0.0-next.55"
"svelte-recaptcha-v2": "^0.0.2"
```

**Comment by basaran** [comment]
hi, it's been very busy lately and I haven't had a chance to address this yet. For some reason, the newer version of sveltekit is having trouble bundling the dependencies. Can you try deleting the `node_modules/.vite` folder and disabling the sveltekit during dev and see if that works?

I will have to create a ticket with the upstream to look into this, another option would be to clone the component from git and strip out the debug import and statements.  A simple find and replace should do the trick.

**Comment by Iuriy-Budnikov** [comment]
+1

**Comment by Zachiah** [comment]
Just add `debug` to your `svelte.config.js.kit.vite.optimizeDeps.include`

**Comment by basaran** [comment]
Hello, I will make a new push to NPM this week, and will sort this out.
